### PR TITLE
Updating transpiler to support Diamond Pattern

### PR DESCRIPTION
**Pull request by SuperGNUS**
This branch should be added to your branches and not merged to master (if you don't want to).

It is first alpha of conversion of OpenZeppelin contracts to use Diamond Pattern and storage (EIP 2535).

Once it can properly convert OZ contracts to the new pattern, I'll update and do pull requests to your repo 'diamond' branch

### CODE REVIEW

**Comment by frangio** [comment]
Can you explain what this feature does? This sounds like it could be relevant for a future version of OpenZeppelin Contracts (https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2964) but not in the near future so we're not likely to merge it now.

**Comment by GVTopCoder** [comment]
We should really merge this code into the transpiler.  Some of the changes here include a significant speedup of the transpile times (about 1 second for OpenZeppelin v4.5 compared to 10-20+ seconds, using quick Map<> lookups for things.

**Comment by frangio** [comment]
@GVTopCoder I'm willing to merge this as long as diamond storage is behind a flag, but this is a big PR and I can't prioritize it.

I also need you to at leasty briefly describe in words the way that this was implemented.

**Comment by GVTopCoder** [comment]
Yes, the implementation is behind a new -E flag in the options and passed to a few transformations (typescript code)

Two new Transformations (diamond access & diamond storage) and I modified a few others.  I sped up the ast-resolver code by pre-building some mappings, for SourceUnit & Contract Definitions I add all the Nodes to a map of Map<id: number, node: Node> in the constructor.  So now if you want to resolve a node it can quickly do a nLogN lookup (maps use red-black trees and are super fast).

The diamond storage transform, strips public variables/non-const and puts them in a library file, i.e. AccessStorage.sol for slot access, grouping and I copy the comments as well for the variable.

One other transform I added was the ability to generate public getters since the code will not be generated by SolC any more because the storage data is in a library.  I figured out how to do this from the hardhat code.

The code should run just like your previous code if the -E is not specified, I did test that before I added the public getters code, so I should really reverify that.

**Pull request closed without merging**
